### ISSUE TITLE
Hardcoded kojihub endpoint

### ISSUE THREAD

**Issue by TristanCacqueray** [juhp/koji-hs#1]
The hub string is hard coded in `Fedora.Koji.Api`, would it be possible to update the api to support custom endpoint?

**Comment by juhp** [comment]
Yes, was thinking the same thing recently.
Not quite sure why I thought this was okay ;-)  probably just being lazy initially.

**Comment by TristanCacqueray** [comment]
I suppose using `unsafePerformIO getEnv` is not an option... How about we change all the signature to include the url as the first argument?

**Comment by juhp** [comment]
Yes, I like this simple solution, thanks.

I am also doing the same in pagure-hs and pdc-hs.
